---
driver:
  name: docker

driver_config:
  volume: /root/.waffles:/root/.waffles
  provision_command: curl -L https://www.opscode.com/chef/install.sh | bash

provisioner:
  name: shell

platforms:
  - name: ubuntu-12.04
    provisioner:
      script: test/provision/shell/ubuntu1204.sh
  - name: ubuntu-14.04
    provisioner:
      script: test/provision/shell/ubuntu1404.sh
  - name: ubuntu-14.04-augeas
    provisioner:
      script: test/provision/shell/ubuntu1404_augeas.sh
  - name: ubuntu-14.04-apache
    provisioner:
      script: test/provision/shell/ubuntu1404_apache.sh
  - name: ubuntu-14.04-mysql
    provisioner:
      script: test/provision/shell/ubuntu1404_mysql.sh
  - name: ubuntu-14.04-rabbitmq
    provisioner:
      script: test/provision/shell/ubuntu1404_rabbitmq.sh

suites:
  - name: ubuntu1204
    includes:
      - ubuntu-12.04
  - name: ubuntu1404
    includes:
      - ubuntu-14.04
  - name: ubuntu1404_augeas
    includes:
      - ubuntu-14.04-augeas
  - name: ubuntu1404_apache
    includes:
      - ubuntu-14.04-apache
  - name: ubuntu1404_mysql
    includes:
      - ubuntu-14.04-mysql
  - name: ubuntu1404_rabbitmq
    includes:
      - ubuntu-14.04-rabbitmq

